import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const resources = {
  fr:{translation:{hello:'Bonjour Cédric',overview:"Vue d'ensemble du parc matériel",dashboard:'Tableau de bord',equipment:'Équipements',worksites:'Chantiers',inspections:'Contrôles',movements:'Mouvements',documents:'Documents',products:'Produits / FDS',admin:'Administration',scan:'Scanner',newEquipment:'Nouvel équipement',search:'Rechercher un n° VMA, série, appareil, personne, camionnette, chantier…',active:'ÉQUIPEMENTS ACTIFS',toInspect:'À CONTRÔLER',quarantine:'NOK / QUARANTAINE',compliance:'CONFORMITÉ DU PARC',follow:'Équipements à suivre',priority:'Échéances et anomalies prioritaires',seeAll:'Voir tout',location:'LOCALISATION',nextInspection:'PROCHAIN CONTRÔLE',status:'STATUT',compliant:'Conforme',due:'À contrôler',expired:'Échu',toHandle:'à traiter',overdue:'Échus',days7:'≤ 7 jours',days30:'8–30 jours',openRound:'Ouvrir la tournée de contrôle',quick:'Accès rapide',quickSub:'Actions terrain les plus utilisées',identify:'Identifier un appareil',identifySub:'QR ou numéro',doInspection:'Effectuer un contrôle',doInspectionSub:'Fiche adaptée automatiquement',assign:'Affecter / déplacer',assignSub:'Chantier, véhicule, stock…',openSds:'Ouvrir une FDS',openSdsSub:'Recherche produit',equipmentManagement:'Gestion des équipements',entity:'Entité'}},
  nl:{translation:{hello:'Hallo Cédric',overview:'Overzicht van het materieelpark',dashboard:'Dashboard',equipment:'Materieel',worksites:'Werven',inspections:'Keuringen',movements:'Bewegingen',documents:'Documenten',products:'Producten / VIB',admin:'Beheer',scan:'Scannen',newEquipment:'Nieuw materieel',search:'Zoek VMA-nr., serienummer, toestel, persoon, bestelwagen, werf…',active:'ACTIEF MATERIEEL',toInspect:'TE CONTROLEREN',quarantine:'NOK / QUARANTAINE',compliance:'CONFORMITEIT PARK',follow:'Op te volgen materieel',priority:'Prioritaire termijnen en afwijkingen',seeAll:'Alles bekijken',location:'LOCATIE',nextInspection:'VOLGENDE KEURING',status:'STATUS',compliant:'Conform',due:'Te controleren',expired:'Vervallen',toHandle:'te behandelen',overdue:'Vervallen',days7:'≤ 7 dagen',days30:'8–30 dagen',openRound:'Controleronde openen',quick:'Snelle toegang',quickSub:'Meest gebruikte terreinacties',identify:'Toestel identificeren',identifySub:'QR of nummer',doInspection:'Controle uitvoeren',doInspectionSub:'Aangepaste fiche automatisch',assign:'Toewijzen / verplaatsen',assignSub:'Werf, voertuig, voorraad…',openSds:'VIB openen',openSdsSub:'Product zoeken',equipmentManagement:'Materieelbeheer',entity:'Entiteit'}},
  en:{translation:{hello:'Hello Cédric',overview:'Equipment fleet overview',dashboard:'Dashboard',equipment:'Equipment',worksites:'Worksites',inspections:'Inspections',movements:'Movements',documents:'Documents',products:'Products / SDS',admin:'Administration',scan:'Scan',newEquipment:'New equipment',search:'Search VMA no., serial, equipment, person, van, worksite…',active:'ACTIVE EQUIPMENT',toInspect:'TO INSPECT',quarantine:'NOK / QUARANTINE',compliance:'FLEET COMPLIANCE',follow:'Equipment to follow up',priority:'Priority deadlines and anomalies',seeAll:'View all',location:'LOCATION',nextInspection:'NEXT INSPECTION',status:'STATUS',compliant:'Compliant',due:'To inspect',expired:'Overdue',toHandle:'to process',overdue:'Overdue',days7:'≤ 7 days',days30:'8–30 days',openRound:'Open inspection round',quick:'Quick access',quickSub:'Most used field actions',identify:'Identify equipment',identifySub:'QR or number',doInspection:'Perform inspection',doInspectionSub:'Correct form selected automatically',assign:'Assign / move',assignSub:'Worksite, vehicle, stock…',openSds:'Open SDS',openSdsSub:'Product search',equipmentManagement:'Equipment management',entity:'Entity'}},
  pl:{translation:{hello:'Dzień dobry Cédric',overview:'Przegląd parku sprzętu',dashboard:'Panel główny',equipment:'Sprzęt',worksites:'Budowy',inspections:'Kontrole',movements:'Przemieszczenia',documents:'Dokumenty',products:'Produkty / SDS',admin:'Administracja',scan:'Skanuj',newEquipment:'Nowy sprzęt',search:'Szukaj nr VMA, numeru seryjnego, sprzętu, osoby, pojazdu, budowy…',active:'AKTYWNY SPRZĘT',toInspect:'DO KONTROLI',quarantine:'NOK / KWARANTANNA',compliance:'ZGODNOŚĆ PARKU',follow:'Sprzęt wymagający uwagi',priority:'Priorytetowe terminy i niezgodności',seeAll:'Zobacz wszystko',location:'LOKALIZACJA',nextInspection:'NASTĘPNA KONTROLA',status:'STATUS',compliant:'Zgodny',due:'Do kontroli',expired:'Po terminie',toHandle:'do obsługi',overdue:'Po terminie',days7:'≤ 7 dni',days30:'8–30 dni',openRound:'Otwórz rundę kontroli',quick:'Szybki dostęp',quickSub:'Najczęściej używane działania w terenie',identify:'Zidentyfikuj sprzęt',identifySub:'QR lub numer',doInspection:'Wykonaj kontrolę',doInspectionSub:'Automatycznie dobrany formularz',assign:'Przypisz / przenieś',assignSub:'Budowa, pojazd, magazyn…',openSds:'Otwórz SDS',openSdsSub:'Wyszukaj produkt',equipmentManagement:'Zarządzanie sprzętem',entity:'Jednostka'}}
}
const stored=localStorage.getItem('tooly_language')
const language=['fr','nl','en','pl'].includes(stored||'') ? stored! : 'fr'
void i18n.use(initReactI18next).init({resources,lng:language,fallbackLng:'fr',interpolation:{escapeValue:false}})
export default i18n
